SELECT WRITER_ID, NICKNAME, SUM(b.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD b JOIN USED_GOODS_USER u
ON b.WRITER_ID = u.USER_ID
WHERE b.STATUS = 'DONE'
GROUP BY b.WRITER_ID, u.NICKNAME
HAVING SUM(b.PRICE) >= 700000
ORDER BY TOTAL_SALES

/*
USED_GOODS_BOARD와 USED_GOODS_USER 테이블에서 완료된 중고 거래의 총금액이 70만 원 이상인
--> JOIN, WHERE, GROUP BY, HAVING 절에서 완성

사람의 회원 ID, 닉네임, 총거래금액을 조회하는 SQL문을 작성해주세요.
-- > SELECT
결과는 총거래금액을 기준으로 오름차순 정렬해주세요.
-- > ORDER BY
*/