SELECT TO_NUMBER(SUBSTR(TO_CHAR(START_DATE, 'YYYY-MM'), 6)) MONTH, CAR_ID, COUNT(TO_CHAR(START_DATE, 'YYYY-MM')) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN
(
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
GROUP BY CAR_ID
HAVING COUNT(HISTORY_ID) >= 5
)
AND TO_NUMBER(SUBSTR(TO_CHAR(START_DATE, 'YYYY-MM'), 6)) IN (8,9,10)
GROUP BY CAR_ID, TO_CHAR(START_DATE, 'YYYY-MM')
HAVING COUNT(TO_CHAR(START_DATE, 'YYYY-MM')) > 0
ORDER BY MONTH, CAR_ID DESC
/* 정답
WHERE절에서 서브쿼리를 이용해서 조건기간동안 차량 대여 수가 5이상인 CAR_ID의 정보의 리스트만 가져오고
COUNT 명령어로 5번 이상 대여한 자동차 CAR_ID만 사용하도록 한다.

조건을 만족하는 CAR_ID만을 가져와서 사용하는데 그 내부정보에는 다시 8,9,10월 이외의 데이터가 존재하므로
WHERE절에 AND로 8,9,10 달의 데이터만 사용하도록 조건을 설정한다.

CAR_ID별, MONTH별 대여횟수를 알아야하므로 두개의 조건으로 GROUP BY 해주며
문제에서 특정 월의 대여횟수가 0인경우는 결과에서 제외하라고 했으므로,
HAVING절에서 COUNT 함수로 0 이상인 데이터만 사용하도록 설정한다.
*/


/* 다른 풀이 - 정답아님 (해결중..)
SELECT MON, CAR_ID, COUNT(CAR_ID) RECORDS
FROM (
SELECT  CAR_ID,
CASE TO_CHAR(START_DATE, 'YYYY-MM')
WHEN '2022-08' THEN 8
WHEN '2022-09' THEN 9
ELSE 10
END AS MON
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
GROUP BY CAR_ID
)
GROUP BY CAR_ID, MON
HAVING COUNT(MON) >= 5
ORDER BY MON, CAR_ID DESC

*/