-- JOIN 사용
SELECT BOOK_ID, AUTHOR_NAME, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD')
FROM BOOK b
INNER JOIN AUTHOR a
ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE CATEGORY = '경제'
ORDER BY PUBLISHED_DATE

/* JOIN 없이 정답
SELECT BOOK_ID, AUTHOR_NAME, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD')
FROM BOOK b, AUTHOR a
WHERE b.AUTHOR_ID = a.AUTHOR_ID
AND CATEGORY = '경제'
ORDER BY PUBLISHED_DATE
*/

/*
JOIN없이 문제를 풀었다가 JOIN 을 사용할 줄 알아야할것같아서 JOIN 을 사용해서 다시 풀어봤다.
*/