SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) SALES
FROM PRODUCT p JOIN OFFLINE_SALE o
ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE


/*
JOIN 을 통하여 두 테이블을 묶어주며
PRICE_CODE로 묶어 각 상품의 판매개수와 판매가격을 곱한 값을 전부 더하여 구해준다.
*/
