SELECT SUBSTR(PRODUCT_CODE,1,2) CATEGORY, COUNT(SUBSTR(PRODUCT_CODE,1,2)) PRODUCTS
FROM PRODUCT
GROUP BY SUBSTR(PRODUCT_CODE,1,2)
ORDER BY CATEGORY


/*
문자열 자르기 - SUBSTR 사용
프로그래밍 언어에서 사용되는 문자열 자르기와 사용법 비슷
*/
