SELECT HOUR, COUNT(HOUR) "COUNT"
FROM (SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR
FROM ANIMAL_OUTS
WHERE TO_CHAR(DATETIME, 'HH24') BETWEEN 9 AND 19)
GROUP BY HOUR
ORDER BY HOUR

/*
문제가 어렵다기 보다. HOUR의 형식에 09 가 아닌 9 가 나와야 하기때문에
이 값을 수정해주는 작업을 해줘야하는 문제이다.
*/