SELECT CAR_ID, CAR_TYPE, ROUND(30 * DAILY_FEE * (100 - DISCOUNT_RATE) / 100) AS "FEE"
FROM CAR_RENTAL_COMPANY_CAR a
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b USING(CAR_ID)
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c USING(CAR_TYPE)
WHERE CAR_ID NOT IN (
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR a
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b USING(CAR_ID)
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c USING(CAR_TYPE)
WHERE '2022-11' BETWEEN TO_CHAR(START_DATE, 'YYYY-MM') AND TO_CHAR(END_DATE, 'YYYY-MM'))
GROUP BY CAR_ID, CAR_TYPE, DAILY_FEE, DURATION_TYPE, DISCOUNT_RATE
HAVING DURATION_TYPE = '30일 이상'
AND CAR_TYPE IN ('세단','SUV')
AND ROUND(30 * DAILY_FEE * (100 - DISCOUNT_RATE) / 100) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

/*
2020-11에 대여 불가능한 CAR_ID 추출 -> 가능한 CAR_ID 추출은 더 어려움
대여 불가능한 CAR_ID를 서브쿼리로 하여 메인쿼리의 WHERE절에 NOT IN으로 제외
메인쿼리에서 문제의 조건을 작성해준다.
- 대여가능한 자동차ID, 자동차의 종류, 할인율, 가격을 묶어야 하므로 CAR_ID, CAR_TYPE, DAILY_FEE, DURATION_TYPE, DISCOUNT_RATE로 묶어준다. (대여기간과 할인율은 함께감)
- HAVING 절에서 30일 이상 대여, 자동차 종류는 세단과 SUV, 30일 대여비용이 50~200인 조건을 작성해준다.
- 정렬해주면 끝

*/


-- >> 아래의 쿼리문들은 대여가 불가능한데도 대여가 가능하다고 판단해서 오답

/*
SELECT CAR_ID, CAR_TYPE, ROUND(30 * DAILY_FEE * (100 - DISCOUNT_RATE) / 100) AS "FEE"
FROM CAR_RENTAL_COMPANY_CAR a
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b USING(CAR_ID)
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c USING(CAR_TYPE)
WHERE CAR_TYPE IN ('세단', 'SUV')
AND '2022-11' NOT BETWEEN TO_CHAR(START_DATE, 'YYYY-MM') AND TO_CHAR(END_DATE, 'YYYY-MM')
GROUP BY CAR_ID, CAR_TYPE, DAILY_FEE, DURATION_TYPE, DISCOUNT_RATE
HAVING DURATION_TYPE = '30일 이상'
AND ROUND(30 * DAILY_FEE * (100 - DISCOUNT_RATE) / 100) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
*/

/*
테이블
CAR_RENTAL_COMPANY_CAR , CAR_RENTAL_COMPANY_RENTAL_HISTORY , CAR_RENTAL_COMPANY_DISCOUNT_PLAN
자동차 종류 CAR_TYPE 세단 또는 SUV

대여가능 2022 11 1 부터 2022 11 30 -> 2022 11 대여가능

30일간 대여금액이 50 이상 200 미만

FEE는 정수만 출력

FEE 내림, TYPE 오름, ID 내림

SELECT CAR_ID, CAR_TYPE,ROUND(30 * DAILY_FEE * (100 - DISCOUNT_RATE) / 100) AS "FEE"
FROM CAR_RENTAL_COMPANY_CAR a
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b USING(CAR_ID)
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c USING(CAR_TYPE)
WHERE CAR_TYPE IN ('세단', 'SUV')
AND '2022-11' NOT BETWEEN TO_CHAR(START_DATE, 'YYYY-MM') AND TO_CHAR(END_DATE, 'YYYY-MM')
GROUP BY CAR_ID, CAR_TYPE,DAILY_FEE, DISCOUNT_RATE
HAVING ROUND(30 * DAILY_FEE * (100 - DISCOUNT_RATE) / 100) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

-- > 할인이 적용안되는 데이터까지 할인적용시킴

할인 조건에 따라 할인을 적용시키려고 하려보니 HAVING절에서 조건을 설정하는데 어려움이 있어
조건에 따라 할인을 적용시킨 SELECT절을 서브쿼리로 만들고 이 쿼리문을 가지고 금액 조건을적용한다.
*/