SELECT HISTORY_ID, SUM(DURATION_DATE * CAL_FEE)
FROM
(
SELECT HISTORY_ID , DAILY_FEE, (END_DATE-START_DATE+1) DURATION_DATE,
CASE
    WHEN (END_DATE-START_DATE+1) BETWEEN 0 AND 6 THEN DAILY_FEE
    WHEN (END_DATE-START_DATE+1) BETWEEN 7 AND 29 THEN DAILY_FEE * (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')) / 100
    WHEN (END_DATE-START_DATE+1) BETWEEN 30 AND 89 THEN DAILY_FEE * (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상')) / 100
    ELSE DAILY_FEE * (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상')) / 100
END CAL_FEE
FROM CAR_RENTAL_COMPANY_CAR a
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b USING(CAR_ID)
WHERE CAR_TYPE = '트럭'
)
GROUP BY HISTORY_ID
ORDER BY 2 DESC, 1 DESC


/*
CAR_RENTAL_COMPANY_CAR 와 CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블을
CAR_ID 로 연결시켜주고, 문제에서 필요한 데이터는 트럭 데이터이므로 WHERE절에 CAR_TYPE = '트럭'설정
대여기간을 기준으로 0~6은 하루 대여비(DAILY_FEE)는 그대로
7~29 는 CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블에서 7일 이상의 정보를 가져오고
30~89 는 CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블에서 30일 이상의 정보를 가져오고
그 이상(나머지)은 CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블에서 90일 이상의 정보를 가져오도록한다.

이 쿼리문을 서브쿼리로 만들어주고

메인쿼리에서 HISTORY_ID 로 묶어주고 SUM(기간 * 가격) 으로 HISTORY_ID별 대여 금액을 구해준다.

! 항상 날짜계산할때는 시작날짜 <= 대여기간 <= 종료날짜 이므로 종료날짜 - 시작날짜 + 1임을 생각

*/