SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) TOTAL_SALES
FROM AUTHOR NATURAL JOIN
(
SELECT BOOK_ID, PRICE, SALES, CATEGORY, AUTHOR_ID
FROM BOOK NATURAL JOIN
(SELECT BOOK_ID , SALES
FROM BOOK_SALES
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01')
)
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC

/*
1. BOOK_SALES 테이블에서 2022-01에 판매된 데이터만 구분 (BOOK_ID)
2. BOOK 테이블과 BOOK_SALES를 조인하여 2022-01에 판매된 데이터의 정보를 가져옴
3. AUTHOR 테이블과 2번 테이블을 조인하여 AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES 정보를 가져옴
4. TOTAL_SALES을 구하기 위해서는 AUTHOR_ID, AUTHOR_NAME, CATEGORY로 그룹화 하여 계산
*/

/*
판매량 - BOOK_SALES
판매가 - BOOK
저자 - BOOK, AUTHOR
저자명 - AUTHOR
카테고리 - BOOK
*/