SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD')
FROM REST_REVIEW a NATURAL JOIN MEMBER_PROFILE
WHERE MEMBER_ID IN (
SELECT a.MEMBER_ID
FROM MEMBER_PROFILE a JOIN REST_REVIEW b
ON a.MEMBER_ID = b.MEMBER_ID
GROUP BY a.MEMBER_ID
HAVING COUNT(b.REVIEW_ID) =
(SELECT MAX(COUNT(b.REVIEW_ID))
FROM MEMBER_PROFILE a JOIN REST_REVIEW b
ON a.MEMBER_ID = b.MEMBER_ID
GROUP BY a.MEMBER_ID)
)
ORDER BY REVIEW_DATE, REVIEW_TEXT


/*
리뷰를 가장 많이 작성한 회원
-- > 서브쿼리로 각 유저의 리뷰 최대수를 계산해 전체 리뷰 최대수를 계산
-- > 리뷰최대로 작성한 유저의 목록을 가져옴
해당 유저들의 리뷰를 가져옴
-- > JOIN을 통해 데이터를 가져와 출력해주며 날짜의 형식을 예시와 같이 출력해야 정답처리
*/