SELECT i.REST_ID REST_ID, i.REST_NAME REST_NAME, i.FOOD_TYPE FOOD_TYPE, i.FAVORITES FAVORITES, i.ADDRESS ADDRESS ,ROUND(SUM(r.REVIEW_SCORE)/COUNT(r.REVIEW_SCORE),2) SCORE
FROM REST_REVIEW r, REST_INFO i
WHERE i.REST_ID = r.REST_ID 
AND i.ADDRESS LIKE '서울%'
GROUP BY i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC

/*
서울에 위치한 식당과 관련된 정보를 불러와야 하므로 먼저
REST_REVIEW, REST_INFO 를 REST_ID로 연결시켜주고
주소에 "서울" 이들어간 단어가 존재한 데이터만 사용하도록 한다.
그룹화는 조건에 맞게 설정해주고 조건에 맞는 출력을 해주면 된다.
*/
