SELECT a.PRODUCT_ID, a.PRODUCT_NAME, SUM(a.PRICE * b.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT a JOIN FOOD_ORDER b
ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE TO_CHAR(b.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY a.PRODUCT_ID, a.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID

/*
FOOD_PRODUCT와 FOOD_ORDER 테이블을 묶어주고 생산일이 '2022-05'의 데이터만 사용하며,
PRODUCT_ID와 PRODUCT_NAME 로 묶어주고 SELECT 절에서 가격과 주문수량을 곱한 데이터를 모두 더해준다.

*/